Improvements to ViewItemDelegate and Filtering
shotgunsoftware/tk-framework-qtwidgets pull request #121
Opened 2022-04-01 15:32 UTC by staceyoue

- Support drawing Check Box, Radio Button, Progress Bar
- Render disabled buttons as greyed out
- Modify GroupedItemView to select group header items
- Improve mouse click event handling
- Improve sizeHint height to account for actions height
- Specify accepted fields only for filtering

2022-07-06 10:22 UTC, 000paradox000 requested changes
LGTM Please review my comment on icon file names

2022-07-06 14:51 UTC, staceyoue commented on python/activity_stream/widget_note.py
> +        """ """
I didn't actually add this function here -- this is just the pre-commit formatting that has modified the file.

2022-07-06 15:00 UTC, staceyoue commented on python/filtering/filter_definition.py
> +        Get or set the fields that will are accepted when building the filter definition.
For properties in python, only the `getter` function's docstring is displayed, so it is suggested to indicate that this property can set the value, if there is a setter function defined for it.

For example, if you run `help(class)` you'll only see the `getter` docstrings that are defined (the setter docstrings are ignored)

2022-07-06 15:02 UTC, staceyoue commented on python/filtering/filter_definition.py
> +        Set this list to None or empty to accept all fields.
How about:

>         Set the value of this property None or the empty list if the filter should accept all given fields (e.g. it does not ignore any fields).

2022-07-06 15:26 UTC, 000paradox000 approved these changes
LGTM thanks for the good job

2022-07-14 10:02 UTC, 000paradox000 reviewed
Very very good job. 

Just some comments:
- Method names could be more pythonic if possible
- There are many codecov warnings. Could be reduced easily?

2022-07-14 21:25 UTC, merged